### ISSUE TITLE
3D data

### ISSUE THREAD

**Issue by rajlakshmi-sawale** [chenhungling/CaimanGUI#1]
Hi @chenhungling, 
Does the GUI work on 3D data? I have 3D data and I'm getting this error when I try to load it:
Can we solve this?
```
(caiman) C:\Users\au711234\CaimanGUI\gui>python caiman_gui.py
Traceback (most recent call last):
  File "C:\Users\au711234\CaimanGUI\gui\caiman_gui.py", line 126, in <lambda>
    openHDF5.triggered.connect(lambda: self.load_data(click=True))
  File "C:\Users\au711234\CaimanGUI\gui\caiman_gui.py", line 243, in load_data
    img_components = [A[:,i].reshape(dims,order='F').toarray() for i in range(A.shape[1])]
  File "C:\Users\au711234\CaimanGUI\gui\caiman_gui.py", line 243, in <listcomp>
    img_components = [A[:,i].reshape(dims,order='F').toarray() for i in range(A.shape[1])]
  File "C:\ProgramData\Anaconda3\envs\caiman\lib\site-packages\scipy\sparse\_base.py", line 161, in reshape
    shape = check_shape(args, self.shape, allow_1d=is_array)
  File "C:\ProgramData\Anaconda3\envs\caiman\lib\site-packages\scipy\sparse\_sputils.py", line 362, in check_shape
    raise ValueError('matrix shape must be two-dimensional')
ValueError: matrix shape must be two-dimensional
```

**Comment by chenhungling** [comment]
Hi Rajlakshmi,

Sorry that our GUI was not designed to take 3D data but rather focused on
time series of single plane data. If you have only a few planes with no
overlapping cells, you can always split the planes and treat them
independently.

Best regards,
Hung-Ling
